version: '3.8'

services:
  db-postgres:
    image: postgres:15-alpine
    container_name: pedidos-db
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: pedidos-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

  app-pedidos:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pedidos-app
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db-postgres
      - rabbitmq

volumes:
  pgdata:
